"""second one

Revision ID: 499a4954bb08
Revises: bb2d732f4052
Create Date: 2025-06-01 19:46:34.354440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '499a4954bb08'
down_revision = 'bb2d732f4052'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statistics',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('agree_count', sa.Integer(), nullable=False),
    sa.Column('disagree_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.drop_table('statistics_blabla')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statistics_blabla',
    sa.Column('question_id', sa.INTEGER(), nullable=False),
    sa.Column('agree_count', sa.INTEGER(), nullable=False),
    sa.Column('disagree_count', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.drop_table('statistics')
    # ### end Alembic commands ###
