"""Add Category model and link to Question

Revision ID: 9fcf077397cc
Revises: 499a4954bb08
Create Date: 2025-06-01 21:57:21.872312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fcf077397cc'
down_revision = '499a4954bb08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_category', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'categories', ['id_category'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_category')

    op.drop_table('categories')
    # ### end Alembic commands ###
